# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddingMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('artist_name', models.CharField(max_length=200)),
                ('album_name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Music_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_list', models.CharField(max_length=200)),
                ('num1', models.CharField(blank=True, max_length=100)),
                ('num2', models.CharField(blank=True, max_length=100)),
                ('num3', models.CharField(blank=True, max_length=100)),
                ('num4', models.CharField(blank=True, max_length=100)),
                ('num5', models.CharField(blank=True, max_length=100)),
                ('num6', models.CharField(blank=True, max_length=100)),
                ('num7', models.CharField(blank=True, max_length=100)),
                ('num8', models.CharField(blank=True, max_length=100)),
                ('num9', models.CharField(blank=True, max_length=100)),
                ('num10', models.CharField(blank=True, max_length=100)),
                ('num11', models.CharField(blank=True, max_length=100)),
                ('num12', models.CharField(blank=True, max_length=100)),
                ('num13', models.CharField(blank=True, max_length=100)),
                ('num14', models.CharField(blank=True, max_length=100)),
                ('num15', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='addingmusic',
            name='album_name_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.Music_list'),
        ),
        migrations.AddField(
            model_name='addingmusic',
            name='artist_name_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.Album'),
        ),
    ]
