# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import music_player.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddingMusicall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('artist_name', models.CharField(max_length=200)),
                ('album_name', models.CharField(max_length=200, unique=True)),
                ('origin', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('photo', models.ImageField(upload_to='album/photos')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_place', models.CharField(max_length=200)),
                ('artist_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('song1', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song2', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song3', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song4', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song5', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song6', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song7', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song8', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song9', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song10', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song11', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song12', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song13', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song14', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
                ('song15', models.FileField(blank=True, upload_to=music_player.models.get_album_name)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_album_list',
            field=models.ManyToManyField(to='music_player.Playlist'),
        ),
    ]
