# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddingMusic',
            new_name='AddingMusicall',
        ),
    ]
