# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingmusicall',
            old_name='photo',
            new_name='artist_photo',
        ),
        migrations.AlterField(
            model_name='addingmusicall',
            name='album_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.Playlist'),
        ),
        migrations.AlterField(
            model_name='addingmusicall',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.Artist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='album_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
