# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_auto_20160914_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingmusicall',
            old_name='artist_photo',
            new_name='album_photo',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_photo',
            field=models.ImageField(default=1, upload_to='artist/photos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_album_list',
            field=models.ManyToManyField(blank=True, to='music_player.Playlist'),
        ),
    ]
