# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_auto_20160914_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addingmusicall',
            name='album_photo',
        ),
        migrations.AddField(
            model_name='playlist',
            name='album_photo',
            field=models.ImageField(default=1, upload_to='album/photos'),
            preserve_default=False,
        ),
    ]
