# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0004_auto_20160914_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingmusicall',
            old_name='album_name',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='addingmusicall',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
