# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0005_auto_20160914_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='Joshua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='Playschool'),
            preserve_default=False,
        ),
    ]
