# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0006_auto_20160914_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
